// AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.
import { fetchTasks } from "./fetchTasks/fetchTasks.ts";
import { updateTask } from "./updateTask/updateTask.ts";

export type ActorRegistration = {
  parentFsmName: string;
  parentFsmVersion: string;
  fsmType: string;
  fsmName: string;
  fsmVersion: string;
  fsmLanguage: string;
  handler: (input: unknown) => unknown;
};

export const ACTOR_REGISTRATIONS: ActorRegistration[] = [
  {
    parentFsmName: "taskMachineConfig",
    parentFsmVersion: "v02",
    fsmType: "promise",
    fsmName: "fetchTasks",
    fsmVersion: "v02",
    fsmLanguage: "typescript",
    handler: fetchTasks,
  },
  {
    parentFsmName: "taskMachineConfig",
    parentFsmVersion: "v02",
    fsmType: "promise",
    fsmName: "updateTask",
    fsmVersion: "v02",
    fsmLanguage: "typescript",
    handler: updateTask,
  },
];
