// AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.
import { checkTirePressure } from "./checkTirePressure/checkTirePressure.ts";
import { checkOilPressure } from "./checkOilPressure/checkOilPressure.ts";
import { checkCoolantLevel } from "./checkCoolantLevel/checkCoolantLevel.ts";
import { checkBattery } from "./checkBattery/checkBattery.ts";

export type ActorRegistration = {
  parentFsmName: string;
  parentFsmVersion: string;
  fsmType: string;
  fsmName: string;
  fsmVersion: string;
  fsmLanguage: string;
  handler: (input: unknown) => unknown;
};

export const ACTOR_REGISTRATIONS: ActorRegistration[] = [
  {
    parentFsmName: "vitalsWorkflow",
    parentFsmVersion: "v01",
    fsmType: "internalAsyncOperation",
    fsmName: "checkTirePressure",
    fsmVersion: "v01",
    fsmLanguage: "typescript",
    handler: checkTirePressure,
  },
  {
    parentFsmName: "vitalsWorkflow",
    parentFsmVersion: "v01",
    fsmType: "internalAsyncOperation",
    fsmName: "checkOilPressure",
    fsmVersion: "v01",
    fsmLanguage: "typescript",
    handler: checkOilPressure,
  },
  {
    parentFsmName: "vitalsWorkflow",
    parentFsmVersion: "v01",
    fsmType: "internalAsyncOperation",
    fsmName: "checkCoolantLevel",
    fsmVersion: "v01",
    fsmLanguage: "typescript",
    handler: checkCoolantLevel,
  },
  {
    parentFsmName: "vitalsWorkflow",
    parentFsmVersion: "v01",
    fsmType: "internalAsyncOperation",
    fsmName: "checkBattery",
    fsmVersion: "v01",
    fsmLanguage: "typescript",
    handler: checkBattery,
  },
];
