module pgfsm/async-op-worker-sdk

go 1.19

require fsm-core-example/go-actors-registry-generated v0.0.0

replace fsm-core-example/go-actors-registry-generated => ../../../../../apps/fsm-core-example/go-actors-registry-generated

// Go's replace directives are only honored in the module actually being
// built, not in a dependency's own go.mod -- they don't propagate
// transitively. So even though go-actors-registry-generated (above) is what
// logically imports each actor module, THIS go.mod also needs its own
// require+replace per actor, or the build can't resolve them. Regenerated by
// fsm-compiler-ts's generate-async-logic -- do not edit by hand.
// --- BEGIN fsm-compiler-ts generated actor requires ---
require fsm-core-example/creditcheck/v01/go/actors/checkreportstable v0.0.0
replace fsm-core-example/creditcheck/v01/go/actors/checkreportstable => ../../../../../apps/fsm-core-example/fsm/creditCheck/v01/go/actors/CheckReportsTable
// --- END fsm-compiler-ts generated actor requires ---
