// AUTO-GENERATED from actors-registry-aggregate.eta — do not edit directly.
// Run `deno task generate:templates` after editing the .eta source.
import { eta } from "../eta-instance.ts";

const compiled = eta.compile(
  '// AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.\npackage generatedregistry\n\nimport (\n<% for (const imp of it.imports) { -%>\n\t<%~ imp.alias %> "<%~ imp.modulePath %>"\n<% } -%>\n)\n\ntype ActorRegistration struct {\n\tParentFsmName    string\n\tParentFsmVersion string\n\tFsmType          string\n\tFsmName          string\n\tFsmVersion       string\n\tFsmLanguage      string\n\tHandler          func(input any) (any, error)\n}\n\nfunc ActorRegistrations() []ActorRegistration {\n\treturn []ActorRegistration{\n<% for (const a of it.actors) { -%>\n\t\t{\n\t\t\tParentFsmName:    <%~ JSON.stringify(a.parentFsmName) %>,\n\t\t\tParentFsmVersion: <%~ JSON.stringify(a.parentFsmVersion) %>,\n\t\t\tFsmType:          <%~ JSON.stringify(a.fsmType) %>,\n\t\t\tFsmName:          <%~ JSON.stringify(a.fsmName) %>,\n\t\t\tFsmVersion:       <%~ JSON.stringify(a.fsmVersion) %>,\n\t\t\tFsmLanguage:      <%~ JSON.stringify(a.fsmLanguage) %>,\n\t\t\tHandler:          <%~ a.alias %>.<%~ a.exportedName %>,\n\t\t},\n<% } -%>\n\t}\n}\n',
);

export const render: (input: unknown) => string = (input) =>
  compiled.call(eta, input as object);
