// AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.
// Wire protocol for the gateway <-> per-language worker sidecar connection.
//
// Go port of the gateway's sidecar/protocol.ts. Wire shapes must match that
// file byte-for-byte (same JSON key names, same framing) since a Go worker
// process and the TypeScript-hosted gateway talk this protocol to each
// other over the same Unix socket.
//
// Framing: 4-byte big-endian length prefix + UTF-8 JSON payload — chosen
// over newline/stdio framing so a worker's own prints can never corrupt the
// RPC channel.
package main

import (
	"encoding/binary"
	"encoding/json"
	"fmt"
	"io"
	"net"
	"sync/atomic"
	"time"
)

type WireEnvelope struct {
	V        string          `json:"v"`
	ID       string          `json:"id"`
	Type     string          `json:"type"`
	TsUnixMs int64           `json:"ts_unix_ms"`
	Source   string          `json:"source"`
	Target   string          `json:"target"`
	TraceID  *string         `json:"trace_id,omitempty"`
	Body     json.RawMessage `json:"body"`
}

// One actor entrypoint a worker process serves. Mirrors the compiler's
// generated registry identity fields — ActorKey() is what the gateway
// routes on.
type RegisteredActor struct {
	ParentFsmName    string `json:"parentFsmName"`
	ParentFsmVersion string `json:"parentFsmVersion"`
	FsmType          string `json:"fsmType"`
	FsmName          string `json:"fsmName"`
	FsmVersion       string `json:"fsmVersion"`
	FsmLanguage      string `json:"fsmLanguage"`
}

func ActorKey(parentFsmName, parentFsmVersion, fsmType, fsmName, fsmVersion, fsmLanguage string) string {
	return fmt.Sprintf("%s@%s@%s@%s@%s@%s", parentFsmName, parentFsmVersion, fsmType, fsmName, fsmVersion, fsmLanguage)
}

// A monotonic counter is enough uniqueness for envelope ids — the gateway
// never inspects this field's format, only Type and Body (see
// sidecar/gateway.ts's handleConnection), so a real UUID dependency isn't
// needed.
var envelopeIDCounter uint64

func nextEnvelopeID() string {
	n := atomic.AddUint64(&envelopeIDCounter, 1)
	return fmt.Sprintf("%d-%d", time.Now().UnixNano(), n)
}

func MakeEnvelope(msgType, source, target string, body any) (WireEnvelope, error) {
	raw, err := json.Marshal(body)
	if err != nil {
		return WireEnvelope{}, err
	}
	return WireEnvelope{
		V:        "1.0",
		ID:       nextEnvelopeID(),
		Type:     msgType,
		TsUnixMs: time.Now().UnixNano() / int64(time.Millisecond),
		Source:   source,
		Target:   target,
		Body:     raw,
	}, nil
}

func WriteFrame(conn net.Conn, envelope WireEnvelope) error {
	payload, err := json.Marshal(envelope)
	if err != nil {
		return err
	}
	header := make([]byte, 4)
	binary.BigEndian.PutUint32(header, uint32(len(payload)))
	if _, err := conn.Write(header); err != nil {
		return err
	}
	_, err = conn.Write(payload)
	return err
}

// Returns (nil, nil) on a clean EOF (mirrors protocol.ts's readFrame()
// returning null), (nil, err) on a real I/O error.
func ReadFrame(conn net.Conn) (*WireEnvelope, error) {
	header := make([]byte, 4)
	if _, err := io.ReadFull(conn, header); err != nil {
		if err == io.EOF || err == io.ErrUnexpectedEOF {
			return nil, nil
		}
		return nil, err
	}
	length := binary.BigEndian.Uint32(header)

	payload := make([]byte, length)
	if _, err := io.ReadFull(conn, payload); err != nil {
		if err == io.EOF || err == io.ErrUnexpectedEOF {
			return nil, nil
		}
		return nil, err
	}

	var envelope WireEnvelope
	if err := json.Unmarshal(payload, &envelope); err != nil {
		return nil, err
	}
	return &envelope, nil
}
