-- =============================================================
-- fsm_schema used to store the JSON schema for validating FSM definitions
-- 1. store it in fsm_core.config_store table
-- 2. store it in fns that return the JSON schema as a string
-- ============================================================
--
-- Below is the original design note and the two approaches it sketched, kept
-- for context on why fsm_core.config_store (never implemented) was
-- considered and rejected in favor of approach 2, a function. Approach 2
-- itself is no longer hand-maintained here either -- see the pointer comment
-- further down.

-- 1. store it in fsm_core.config_store table (sketched, never implemented --
-- doesn't fit Supabase's declarative-schema-diff model as cleanly as DDL
-- does: seeding this table's row data isn't something `supabase db diff`
-- picks up the way a CREATE FUNCTION/TYPE change is).
-- DROP TABLE IF EXISTS fsm_core.config_store;
-- CREATE TABLE fsm_core.config_store (
--     config_name TEXT,
--     config_value JSON not null,
--     config_version integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY
-- );
--
-- insert into fsm_core.config_store (config_name, config_value) values (
--     'fsm_schema',
--     -- ...the full fsm.machine.schema.v3.json content, hand-copied here...
--     );

-- 2. store it in fns that return the JSON schema as a string
--
-- fsm_core.fsm_json_schema() itself is generated, not hand-maintained here.
-- See 10_ext_helper/fsm_core_json_schema.generated.sql (loaded after this
-- file in file-sort order), generated by
-- packages/database-src/scripts/generate-fsm-json-postgres-types.ts from
-- fsm.machine.schema.v3.json (deno task generate:pg-types). This file used
-- to hand-copy the schema JSON directly into a CREATE FUNCTION statement
-- here, which drifted out of sync with the real schema -- removed in favor
-- of the generated version.

-- ============================================================
-- System sentinel constants as immutable SQL functions.
-- These provide named, queryable origins for parent queue fields
-- in event log rows, replacing NULL for internally-sourced events.
-- ============================================================

CREATE OR REPLACE FUNCTION fsm_core.pg_system_queue_uuid()
  RETURNS uuid LANGUAGE sql IMMUTABLE AS
  $$ SELECT '00000000-0000-0000-0000-000000000000'::uuid $$;

CREATE OR REPLACE FUNCTION fsm_core.pg_system_queue_type()
  RETURNS text LANGUAGE sql IMMUTABLE AS
  $$ SELECT 'POSTGRES_INTERNAL'::text $$;

CREATE OR REPLACE FUNCTION fsm_core.pg_system_event_name()
  RETURNS text LANGUAGE sql IMMUTABLE AS
  $$ SELECT 'POSTGRES_INTERNAL_EVENT'::text $$;

CREATE OR REPLACE FUNCTION fsm_core.api_system_queue_uuid()
  RETURNS uuid LANGUAGE sql IMMUTABLE AS
  $$ SELECT '00000000-0000-0000-0000-000000000001'::uuid $$;

CREATE OR REPLACE FUNCTION fsm_core.api_system_queue_type()
  RETURNS text LANGUAGE sql IMMUTABLE AS
  $$ SELECT 'API_INTERNAL'::text $$;

CREATE OR REPLACE FUNCTION fsm_core.api_system_event_name()
  RETURNS text LANGUAGE sql IMMUTABLE AS
  $$ SELECT 'API_INTERNAL_EVENT'::text $$;

-- ============================================================
-- Types for FSM event and queue message data, used in function signatures.
-- ============================================================
CREATE TYPE fsm_core.fsm_event_data_v2 AS (
    "eventType"    text,
    "eventPayload" jsonb,
    "actionType"   text
);

CREATE TYPE fsm_core.fsm_queue_msg_data_v2 AS (
    "eventData"                    fsm_core.fsm_event_data_v2,
    "queueId"                      text,
    "queueType"                    text,
    "queueVersion"                 text,
    "sendToParentQueueId"          uuid,
    "sendToParentQueueType"        text,
    "sendToParentQueueIdEventName" text,
    "queueMsgId"                   bigint,
    "queueMsgDelay"                integer,
    "queueFnName"                  text
);
