-- fsm_core.fsm_json_schema() — returns the FSM JSON schema as JSON — is
-- generated, not hand-maintained here. See
-- 10_ext_helper/fsm_core_json_schema.generated.sql (loaded after this file
-- in file-sort order), generated by
-- packages/database-src/scripts/generate-fsm-json-postgres-types.ts from
-- fsm.machine.schema.v3.json (deno task generate:pg-types). Previously this
-- file hand-copied the schema JSON directly into a CREATE FUNCTION
-- statement (and, commented out, an alternate fsm_core.config_store
-- table-backed design) — both drifted out of sync with the real schema, so
-- both were removed in favor of the generated version.

-- ============================================================
-- System sentinel constants as immutable SQL functions.
-- These provide named, queryable origins for parent queue fields
-- in event log rows, replacing NULL for internally-sourced events.
-- ============================================================

CREATE OR REPLACE FUNCTION fsm_core.pg_system_queue_uuid()
  RETURNS uuid LANGUAGE sql IMMUTABLE AS
  $$ SELECT '00000000-0000-0000-0000-000000000000'::uuid $$;

CREATE OR REPLACE FUNCTION fsm_core.pg_system_queue_type()
  RETURNS text LANGUAGE sql IMMUTABLE AS
  $$ SELECT 'POSTGRES_INTERNAL'::text $$;

CREATE OR REPLACE FUNCTION fsm_core.pg_system_event_name()
  RETURNS text LANGUAGE sql IMMUTABLE AS
  $$ SELECT 'POSTGRES_INTERNAL_EVENT'::text $$;

CREATE OR REPLACE FUNCTION fsm_core.api_system_queue_uuid()
  RETURNS uuid LANGUAGE sql IMMUTABLE AS
  $$ SELECT '00000000-0000-0000-0000-000000000001'::uuid $$;

CREATE OR REPLACE FUNCTION fsm_core.api_system_queue_type()
  RETURNS text LANGUAGE sql IMMUTABLE AS
  $$ SELECT 'API_INTERNAL'::text $$;

CREATE OR REPLACE FUNCTION fsm_core.api_system_event_name()
  RETURNS text LANGUAGE sql IMMUTABLE AS
  $$ SELECT 'API_INTERNAL_EVENT'::text $$;

-- ============================================================
-- Types for FSM event and queue message data, used in function signatures.
-- ============================================================
CREATE TYPE fsm_core.fsm_event_data_v2 AS (
    "eventType"    text,
    "eventPayload" jsonb,
    "actionType"   text
);

CREATE TYPE fsm_core.fsm_queue_msg_data_v2 AS (
    "eventData"                    fsm_core.fsm_event_data_v2,
    "queueId"                      text,
    "queueType"                    text,
    "queueVersion"                 text,
    "sendToParentQueueId"          uuid,
    "sendToParentQueueType"        text,
    "sendToParentQueueIdEventName" text,
    "queueMsgId"                   bigint,
    "queueMsgDelay"                integer,
    "queueFnName"                  text
);
