// AUTO-GENERATED from actors-registry-aggregate.eta — do not edit directly.
// Run `deno task generate:templates` after editing the .eta source.
import { eta } from "../eta-instance.ts";

const compiled = eta.compile(
  '# AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.\n# Each FSM-version\'s registry is imported statically via a dotted path\n# (fsm-compiler-ts validates every plugin-root/FSM-name folder name is a\n# valid Python identifier before generating this file, precisely so this can\n# be a plain import instead of a runtime file-path load). The plugin root\'s\n# parent directory is added to sys.path so `<%~ it.pluginRootDirName %>` resolves as a\n# namespace package -- Python has no relative-path import syntax like TS\'s\n# `"../../x/y.ts"` or Rust\'s `#[path]`, so this is the static-import\n# equivalent for a sibling directory two levels up.\nimport os\nimport sys\n\n_APP_ROOT = os.path.abspath(\n    os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..")\n)\nif _APP_ROOT not in sys.path:\n    sys.path.insert(0, _APP_ROOT)\n\n<% for (const g of it.groups) { -%>\nfrom <%~ it.pluginRootDirName %>.<%~ g.key.split("/").join(".") %>.python.actors.generated_registry import ACTOR_REGISTRATIONS as <%~ g.alias %>\n<% } -%>\n\nACTOR_REGISTRATIONS = [\n<% for (const g of it.groups) { -%>\n    *<%~ g.alias %>,\n<% } -%>\n]\n',
);

export const render: (input: unknown) => string = (input) =>
  compiled.call(eta, input as object);
