// AUTO-GENERATED from actors-registry-aggregate.eta — do not edit directly.
// Run `deno task generate:templates` after editing the .eta source.
import { eta } from "../eta-instance.ts";

const compiled = eta.compile(
  '# AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.\n# Each FSM-version\'s registry is loaded from a fixed, compiler-generated\n# path -- not a runtime scan -- since Python has no static-import syntax that\n# reaches an arbitrarily-nested sibling directory the way TS/Rust do.\nimport importlib.util\nimport os\n\n_BASE_DIR = os.path.dirname(os.path.abspath(__file__))\n\n\ndef _load_registrations(rel_path):\n    spec = importlib.util.spec_from_file_location(\n        "generated_registry", os.path.join(_BASE_DIR, rel_path)\n    )\n    module = importlib.util.module_from_spec(spec)\n    spec.loader.exec_module(module)\n    return module.ACTOR_REGISTRATIONS\n\n\n<% for (const g of it.groups) { -%>\n<%~ g.alias %> = _load_registrations(<%~ JSON.stringify(`../../${it.pluginRootDirName}/${g.key}/python/actors/generated_registry.py`) %>)\n<% } -%>\n\nACTOR_REGISTRATIONS = [\n<% for (const g of it.groups) { -%>\n    *<%~ g.alias %>,\n<% } -%>\n]\n',
);

export const render: (input: unknown) => string = (input) =>
  compiled.call(eta, input as object);
