// AUTO-GENERATED from actors-registry.eta — do not edit directly.
// Run `deno task generate:templates` after editing the .eta source.
import { eta } from "../eta-instance.ts";

const compiled = eta.compile(
  '# AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.\nimport importlib.util\nimport os\n\n_BASE_DIR = os.path.dirname(os.path.abspath(__file__))\n\n\ndef _load_actor(rel_path, fn_name):\n    spec = importlib.util.spec_from_file_location(\n        fn_name, os.path.join(_BASE_DIR, rel_path)\n    )\n    module = importlib.util.module_from_spec(spec)\n    spec.loader.exec_module(module)\n    return getattr(module, fn_name)\n\n\n<% for (const a of it.actors) { -%>\n<%~ a.src %> = _load_actor(<%~ JSON.stringify(`${a.fileBaseName}/${a.fileBaseName}.py`) %>, <%~ JSON.stringify(a.src) %>)\n<% } -%>\n\nACTOR_REGISTRATIONS = [\n<% for (const a of it.actors) { -%>\n    {\n        "parent_fsm_name": <%~ JSON.stringify(a.parentFsmName) %>,\n        "parent_fsm_version": <%~ JSON.stringify(a.parentFsmVersion) %>,\n        "fsm_type": <%~ JSON.stringify(a.fsmType) %>,\n        "fsm_name": <%~ JSON.stringify(a.fsmName) %>,\n        "fsm_version": <%~ JSON.stringify(a.fsmVersion) %>,\n        "fsm_language": <%~ JSON.stringify(a.fsmLanguage) %>,\n        "handler": <%~ a.src %>,\n    },\n<% } -%>\n]\n',
);

export const render: (input: unknown) => string = (input) =>
  compiled.call(eta, input as object);
