// AUTO-GENERATED from worker-sdk-requirements.eta — do not edit directly.
// Run `deno task generate:templates` after editing the .eta source.
import { eta } from "../eta-instance.ts";

const compiled = eta.compile(
  "# AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.\n# grpcio/protobuf back the generated pgfsm.sidecargateway.v1 client stub\n# (packages/fsm-proto-codegen/gen/python/) sdk.py imports — see #100.\ngrpcio>=1.60,<2\nprotobuf>=4,<8\n",
);

export const render: (input: unknown) => string = (input) =>
  compiled.call(eta, input as object);
