// AUTO-GENERATED from worker-sdk-requirements.eta — do not edit directly.
// Run `deno task generate:templates` after editing the .eta source.
import { eta } from "../eta-instance.ts";

const compiled = eta.compile(
  "# AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.\n# The generated pgfsm.{activitygateway,sidecargateway}.v1 client stub\n# (packages/fsm-proto-codegen/gen/python/) sdk.py imports, installed\n# editable rather than reached via a sys.path.insert relative path — see\n# #100, #106. grpcio/protobuf come along as its own dependencies.\n-e <%~ it.protoGenPythonEditablePath %>\n",
);

export const render: (input: unknown) => string = (input) =>
  compiled.call(eta, input as object);
