// AUTO-GENERATED from worker-sdk-requirements-legacy.eta — do not edit directly.
// Run `deno task generate:templates` after editing the .eta source.
import { eta } from "../eta-instance.ts";

const compiled = eta.compile(
  "# AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.\n# No external dependencies required — stdlib only (socket, struct, json,\n# threading, asyncio, argparse).\n",
);

export const render: (input: unknown) => string = (input) =>
  compiled.call(eta, input as object);
