// AUTO-GENERATED from actors-registry.eta — do not edit directly.
// Run `deno task generate:templates` after editing the .eta source.
import { eta } from "../eta-instance.ts";

const compiled = eta.compile(
  "// AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.\n#[path = \"mod.rs\"]\nmod actors;\n\npub struct ActorRegistration {\n    pub parent_fsm_name: &'static str,\n    pub parent_fsm_version: &'static str,\n    pub fsm_type: &'static str,\n    pub fsm_name: &'static str,\n    pub fsm_version: &'static str,\n    pub fsm_language: &'static str,\n    pub handler: fn(serde_json::Value) -> serde_json::Value,\n}\n\npub fn actor_registrations() -> Vec<ActorRegistration> {\n    vec![\n<% for (const a of it.actors) { -%>\n        ActorRegistration {\n            parent_fsm_name: <%~ JSON.stringify(a.parentFsmName) %>,\n            parent_fsm_version: <%~ JSON.stringify(a.parentFsmVersion) %>,\n            fsm_type: <%~ JSON.stringify(a.fsmType) %>,\n            fsm_name: <%~ JSON.stringify(a.fsmName) %>,\n            fsm_version: <%~ JSON.stringify(a.fsmVersion) %>,\n            fsm_language: <%~ JSON.stringify(a.fsmLanguage) %>,\n            handler: actors::<%~ a.src %>,\n        },\n<% } -%>\n    ]\n}\n",
);

export const render: (input: unknown) => string = (input) =>
  compiled.call(eta, input as object);
