// AUTO-GENERATED from worker-sdk-cargo-toml.eta — do not edit directly.
// Run `deno task generate:templates` after editing the .eta source.
import { eta } from "../eta-instance.ts";

const compiled = eta.compile(
  '# AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.\n[package]\nname = "pgfsm-async-op-worker-sdk"\nversion = "0.1.0"\nedition = "2021"\n\n[[bin]]\nname = "worker-sdk-rust"\npath = "src/main.rs"\n\n[dependencies]\nctrlc = "3"\nserde = { version = "1", features = ["derive"] }\nserde_json = "1"\n# tonic/prost/tonic-prost back the generated pgfsm.sidecargateway.v1 client\n# sdk.rs uses directly (Endpoint, transport types, etc) -- see #100. All\n# three must share a major version (see fsm-proto-codegen\'s README).\ntokio = { version = "1", features = ["rt-multi-thread", "macros", "time", "sync"] }\ntokio-stream = "0.1"\ntonic = { version = "0.14", features = ["transport"] }\ntonic-prost = "0.14"\nprost = "0.14"\n# The generated pgfsm.{activitygateway,sidecargateway}.v1 message/client\n# types themselves, via a real crate boundary instead of a #[path]-included\n# file -- see #106.\npgfsm-proto-codegen = { path = "<%~ it.protoGenRustCratePath %>" }\n',
);

export const render: (input: unknown) => string = (input) =>
  compiled.call(eta, input as object);
