// AUTO-GENERATED from worker-sdk-cargo-toml-legacy.eta — do not edit directly.
// Run `deno task generate:templates` after editing the .eta source.
import { eta } from "../eta-instance.ts";

const compiled = eta.compile(
  '# AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.\n[package]\nname = "pgfsm-async-op-worker-sdk"\nversion = "0.1.0"\nedition = "2021"\n\n[[bin]]\nname = "worker-sdk-rust"\npath = "src/main.rs"\n\n[dependencies]\nctrlc = "3"\nserde = { version = "1", features = ["derive"] }\nserde_json = "1"\n',
);

export const render: (input: unknown) => string = (input) =>
  compiled.call(eta, input as object);
