// AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.
import { helloPgfsm } from "./helloPgfsm/helloPgfsm.ts";
import { helloWorld } from "./helloWorld/helloWorld.ts";

export type ActorRegistration = {
  parentFsmName: string;
  parentFsmVersion: string;
  asyncOperationType: string;
  asyncOperationName: string;
  asyncOperationVersion: string;
  asyncOperationLanguage: string;
  handler: (input: unknown) => unknown;
};

export const ACTOR_REGISTRATIONS: ActorRegistration[] = [
  {
    parentFsmName: "sharedAsyncOperation",
    parentFsmVersion: "v01",
    asyncOperationType: "sharedAsyncOperation",
    asyncOperationName: "helloPgfsm",
    asyncOperationVersion: "v01",
    asyncOperationLanguage: "typescript",
    handler: helloPgfsm,
  },
  {
    parentFsmName: "sharedAsyncOperation",
    parentFsmVersion: "v01",
    asyncOperationType: "sharedAsyncOperation",
    asyncOperationName: "helloWorld",
    asyncOperationVersion: "v01",
    asyncOperationLanguage: "typescript",
    handler: helloWorld,
  },
];
