// AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.
import { helloPgfsm } from "./helloPgfsm/helloPgfsm.ts";
import { helloWorld } from "./helloWorld/helloWorld.ts";

export type ActorRegistration = {
  parentFsmName: string;
  parentFsmVersion: string;
  fsmType: string;
  fsmName: string;
  fsmVersion: string;
  fsmLanguage: string;
  handler: (input: unknown) => unknown;
};

export const ACTOR_REGISTRATIONS: ActorRegistration[] = [
  {
    parentFsmName: "sharedAsyncOperation",
    parentFsmVersion: "v01",
    fsmType: "sharedAsyncOperation",
    fsmName: "helloPgfsm",
    fsmVersion: "v01",
    fsmLanguage: "typescript",
    handler: helloPgfsm,
  },
  {
    parentFsmName: "sharedAsyncOperation",
    parentFsmVersion: "v01",
    fsmType: "sharedAsyncOperation",
    fsmName: "helloWorld",
    fsmVersion: "v01",
    fsmLanguage: "typescript",
    handler: helloWorld,
  },
];
