// AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.
package generatedregistry

import (
	creditcheck_v01_checkreportstable "fsm-core-example/creditcheck/v01/go/actors/checkreportstable"
)

type ActorRegistration struct {
	ParentFsmName    string
	ParentFsmVersion string
	FsmType          string
	FsmName          string
	FsmVersion       string
	FsmLanguage      string
	Handler          func(input any) (any, error)
}

func ActorRegistrations() []ActorRegistration {
	return []ActorRegistration{
		{
			ParentFsmName:    "creditCheck",
			ParentFsmVersion: "v01",
			FsmType:          "internalAsyncOperation",
			FsmName:          "CheckReportsTable",
			FsmVersion:       "v01",
			FsmLanguage:      "go",
			Handler:          creditcheck_v01_checkreportstable.CheckReportsTable,
		},
	}
}
