// AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.
// TypeScript worker SDK: connects to the gateway's sidecar Unix socket,
// registers actors from a compiler-generated registry, and serves invoke
// requests.
//
// Actor discovery is no longer a runtime folder scan + dynamic `import()` —
// `fsm-compiler-ts` generates a static, self-describing registry
// (`ActorRegistration[]`, see `packages/fsm-compiler-ts/src/operation-logic-scaffold.ts`'s
// `writeActorsRegistry`/`writeAggregateActorsRegistry`) that this SDK just
// iterates. `ActorWorker` takes that array directly; the CLI is what wires it
// to a fixed, statically-imported registry file (see cli.ts) — this module
// stays registry-source-agnostic so it's easy to test with a synthetic array.
//
// This is the reference implementation for a compiled-language worker SDK
// (e.g. Rust) to follow — see ADR-003's Activity Gateway revision.

import { getLogger } from "@logtape/logtape";
import {
  actorKey,
  type InvokeBody,
  type InvokeErrorBody,
  type InvokeResultBody,
  makeEnvelope,
  readFrame,
  type RegisterAckBody,
  type RegisterBody,
  type RegisteredActor,
  writeFrame,
} from "../../../../packages/fsm-core-async-op-worker/src/sidecar/protocol.ts";

const logger = getLogger([
  "@pgfsm/worker",
  "async-op-worker-gateway",
  "worker-sdk-ts",
]);

export type ActorHandler = (input: unknown) => unknown | Promise<unknown>;

/** One entry from a compiler-generated actor registry (see module doc comment). */
export type ActorRegistration = {
  parentFsmName: string;
  parentFsmVersion: string;
  fsmType: string;
  fsmName: string;
  fsmVersion: string;
  fsmLanguage: string;
  handler: ActorHandler;
};

const DEFAULT_HEARTBEAT_MS = 5_000;

export interface ActorWorkerOptions {
  workerId: string;
  language: string;
  gatewaySocketPath: string;
  heartbeatMs?: number;
}

// Connects to the gateway's sidecar socket, registers `registrations`, and
// serves invoke requests until the gateway unregisters this worker or
// `stop()` is called.
export class ActorWorker {
  private conn: Deno.Conn | null = null;
  private stopped = false;
  private readonly handlers = new Map<string, ActorHandler>();

  constructor(
    private readonly options: ActorWorkerOptions,
    private readonly registrations: ActorRegistration[],
  ) {}

  async run(): Promise<void> {
    if (this.registrations.length === 0) {
      throw new Error("no actors to register, refusing to start worker");
    }

    const registeredActors: RegisteredActor[] = [];
    for (const reg of this.registrations) {
      this.handlers.set(
        actorKey(
          reg.parentFsmName,
          reg.parentFsmVersion,
          reg.fsmType,
          reg.fsmName,
          reg.fsmVersion,
          reg.fsmLanguage,
        ),
        reg.handler,
      );
      registeredActors.push({
        parentFsmName: reg.parentFsmName,
        parentFsmVersion: reg.parentFsmVersion,
        fsmType: reg.fsmType,
        fsmName: reg.fsmName,
        fsmVersion: reg.fsmVersion,
        fsmLanguage: reg.fsmLanguage,
      });
    }

    const conn = await Deno.connect({
      transport: "unix",
      path: this.options.gatewaySocketPath,
    });
    this.conn = conn;

    const registerBody: RegisterBody = {
      worker_id: this.options.workerId,
      language: this.options.language,
      protocol_version: "1.0",
      actors: registeredActors,
    };

    await writeFrame(
      conn,
      makeEnvelope(
        "register",
        `worker:${this.options.workerId}`,
        "gateway",
        registerBody as unknown as Record<string, unknown>,
      ),
    );

    const ack = await readFrame(conn);
    if (!ack || ack.type !== "register_ack") {
      throw new Error(`expected register_ack but got ${ack?.type ?? "EOF"}`);
    }
    const ackBody = ack.body as unknown as RegisterAckBody;
    if (!ackBody.accepted) {
      throw new Error("gateway rejected registration");
    }

    logger.info(
      "Worker {workerId} registered {count} actor(s) with the gateway",
      { workerId: this.options.workerId, count: registeredActors.length },
    );

    const heartbeat = this.heartbeatLoop(conn);

    try {
      await this.serveLoop(conn);
    } finally {
      this.stopped = true;
      await heartbeat.catch(() => {});
      try {
        conn.close();
      } catch {
        // already closed
      }
    }
  }

  stop(): void {
    this.stopped = true;
    try {
      this.conn?.close();
    } catch {
      // already closed
    }
  }

  private async heartbeatLoop(conn: Deno.Conn): Promise<void> {
    const intervalMs = this.options.heartbeatMs ?? DEFAULT_HEARTBEAT_MS;
    while (!this.stopped) {
      await new Promise((resolve) => setTimeout(resolve, intervalMs));
      if (this.stopped) {
        break;
      }
      await writeFrame(
        conn,
        makeEnvelope(
          "heartbeat",
          `worker:${this.options.workerId}`,
          "gateway",
          { worker_id: this.options.workerId },
        ),
      );
    }
  }

  private async serveLoop(conn: Deno.Conn): Promise<void> {
    while (!this.stopped) {
      const envelope = await readFrame(conn);
      if (!envelope) {
        break;
      }

      if (envelope.type === "cancel") {
        continue;
      }
      if (envelope.type === "unregister") {
        break;
      }
      if (envelope.type !== "invoke") {
        continue;
      }

      await this.handleInvoke(conn, envelope.body as unknown as InvokeBody);
    }
  }

  private async handleInvoke(conn: Deno.Conn, body: InvokeBody): Promise<void> {
    const key = actorKey(
      body.parent_fsm_name,
      body.parent_fsm_version,
      body.fsm_type,
      body.fsm_name,
      body.fsm_version,
      body.fsm_language,
    );
    const handler = this.handlers.get(key);
    const started = performance.now();

    if (!handler) {
      await this.sendError(
        conn,
        body.invoke_id,
        "NOT_FOUND",
        `actor not found: ${key}`,
      );
      return;
    }

    try {
      const output = await Promise.resolve(handler(body.input));
      const durationMs = Math.max(0, Math.round(performance.now() - started));
      const result: InvokeResultBody = {
        invoke_id: body.invoke_id,
        output,
        duration_ms: durationMs,
      };
      await writeFrame(
        conn,
        makeEnvelope(
          "invoke_result",
          `worker:${this.options.workerId}`,
          "gateway",
          result as unknown as Record<string, unknown>,
        ),
      );
    } catch (error) {
      await this.sendError(
        conn,
        body.invoke_id,
        "INTERNAL",
        error instanceof Error ? error.message : "unknown worker error",
      );
    }
  }

  private async sendError(
    conn: Deno.Conn,
    invokeId: string,
    code: string,
    message: string,
  ): Promise<void> {
    const errorBody: InvokeErrorBody = {
      invoke_id: invokeId,
      error: { code, message, retriable: false },
    };
    await writeFrame(
      conn,
      makeEnvelope(
        "invoke_error",
        `worker:${this.options.workerId}`,
        "gateway",
        errorBody as unknown as Record<string, unknown>,
      ),
    );
  }
}
