# AUTO-GENERATED by fsm-compiler-ts. Do not edit directly.
from .checkBureau.checkBureau import checkBureau

ACTOR_REGISTRATIONS = [
    {
        "parent_fsm_name": "creditCheck",
        "parent_fsm_version": "v01",
        "fsm_type": "internalAsyncOperation",
        "fsm_name": "checkBureau",
        "fsm_version": "v01",
        "fsm_language": "python",
        "handler": checkBureau,
    },
]
